### PR TITLE
Fix nan loss for cos comparator

### PR DESCRIPTION
**Pull request by simonepri**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

Closes https://github.com/facebookresearch/PyTorch-BigGraph/issues/53.

## How Has This Been Tested (if it applies)

More tests needs to be added to test the behaviour of the cos comparator when a vector of all zeros is provided to avoid regressions in the future. See https://github.com/facebookresearch/PyTorch-BigGraph/issues/53#issuecomment-502443027.

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by lerks** [comment]
Are you sure that the normalization in the cosine distance comparator is the cause of #53 and that this commit will fix it? I had considered it as a likely culprit when I investigated nan losses in the past but it never turned out to be that: embeddings are "never" really all zeroes. (You might have noticed that, actually, when we pad the batch so that its size becomes a multiple of the chunk size we do add all-zero vectors, which do indeed give a nan score, but when we then apply the mask we ignore those nans; this loss "poisoning" has in fact been helpful to diagnose bugs in the masking). I also remembered that I tried implementing a safety net similar to the one you're doing here (I think mine was something like: if the norm of a vector is zero replace it by one before doing the division) but it had a significant impact on the performance. What is the impact of your change here? Also, what benefit does it bring to do the reciprocal in-place? And why not also the clamp?

**Comment by simonepri** [comment]
> Are you sure that the normalization in the cosine distance comparator is the cause of #53 and that this commit will fix it?

I must admit that I can't say to be 100% sure about this, but that's the only problematic operation I was able to find.

While implementing https://github.com/facebookresearch/PyTorch-BigGraph/pull/67 I had the same `NaN` problem due to the norm, which I solved by clamping the output.

I'll try to see wether I'm able to get this NaN loss somehow again and see whether this actually solves the problem.

> And why not also the clamp?

We can't modify in place the vector computed by the norm operation because otherwise this error is thrown.
image

> Also, what benefit does it bring to do the reciprocal in-place?
* `a.reciprocal()` creates a new tensor with the reciprocals
* `a.clamp_min().reciprocal()` creates a new tensor with the clamped values and then create a new tensor with the reciprocals
* `a.clamp_min()._reciprocal()` `clamp_min()._reciprocal()` does the same but the reciprocals are computed in-place without instantiating a new tensor 

In terms of performance I imagine that an in-place operation it's faster (but I've not tested it).

**Comment by lerks** [comment]
> Do you have any suggested way to benchmark the changes? How do you do it in general?

I usually just try to set up a realistic scenario in ipython and then run `%timeit` on it. Here I would test the full model (in two versions, with the old and with the new comparator), do a forward+backward, with a default batch size.

At some point I did some quite thorough profiling by instrumenting the entire model code with markers to see which parts took the most time. Unfortunately I threw away the code (because I didn't want to merge it and at some point master diverged so much I couldn't apply it anymore) and I can't find the results from back then anymore. Off the top of my head I remember that one of the most surprising findings was that the normalization was taking a really long time (which is why we ended up multiplying each coefficient by the reciprocal of the norm, which we only compute once, rather than dividing).

> In terms of performance I imagine that an in-place operation it's faster (but I've not tested it).
Not really, as allocating memory is fast and also I think PyTorch keeps a cache of tensors. Here's a benchmark with 1,000,000 elements:
```
In [19]: %timeit t.clamp_min(10e-9).reciprocal()
1.29 ms ± 11.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [20]: %timeit t.clamp_min(10e-9).reciprocal_()
1.31 ms ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
I'd go with non-inplace because that's how we do it everywhere else (except in the rare few cases where we're memory-constrained, namely when we handle embedding tables).

**Comment by simonepri** [comment]
> Not really, as allocating memory is fast and also I think PyTorch keeps a cache of tensors. Here's a benchmark with 1,000,000 elements

I run the benchmark too, but I got different results.

On GPU:
 

On CPU:
 



> I'd go with non-inplace because that's how we do it everywhere else (except in the rare few cases where we're memory-constrained, namely when we handle embedding tables).

Ok this makes sense.

**Comment by lerks** [comment]
I ran again the exact same code of your benchmarks (in mine I had initialized `t` with `empty`, now I'm using `rand`) but I'm getting the exact same results as before. Also, I don't see how your CPU and GPU tests are different: there's no mention of GPUs or CUDA in your GPU code.

Anyways, the exact performance of in- vs out-of-place is not what is important here, we should focus on the performance of the entire forward+backward in the cases with and without the `clamp_min`. Did you manage to set up some benchmark there? Do you need assistance?

**Comment by simonepri** [comment]
> Also, I don't see how your CPU and GPU tests are different: there's no mention of GPUs or CUDA in your GPU code.

Sorry I just changed machine type forgetting to add adding the cuda code. I've updated the results.

>  Did you manage to set up some benchmark there? Do you need assistance?

Not yet, I was thinking to run the examples in the example folder with `timeit` as starting point. What do you think?

**Comment by lerks** [comment]
I don't think running the examples would give us a good signal, it would end up measuring everything including all the I/O. Since they are also rather small datasets it might not be able to capture small performance changes. You could still run them and look at the stats that are logged (how many edges per second are processes) to get a rough feeling (i.e., that will tell you if there is a large performance drop) but for anything more fine-grained I think we need a different setup.

**Comment by adamlerer** [comment]
`cos(x, \bar(0))` is not 0, and I don't think it's a great idea to "fix it up to 0" here, because it's masking a likely conceptual error (as was the case in https://github.com/facebookresearch/PyTorch-BigGraph/issues/53#issuecomment-502443027 ). For example, these 0-embeddings will never get a gradient after this change, so you're going to silently get weird behavior.

I think a better answer would be to check if any of the embeddings are identically zero and throw an error. But since nobody has complained since 2019, I'm going to close this. Feel free to reopen with the suggested fix.

**Pull request closed without merging**
